### [NumPy]

다양한 계산 도구를 제공하는 파이썬 라이브러리
- 다량의데이터저장을위한컨테이너(ndarray-NDimensionalArray,N차원배열)제공

- C언어로작성되어속도가빠르고메모리를적게사용한다.

- 행렬계산,난수(randomnumber)생성 푸리에 변환 등

In [ ]:
pip install numpy

In [ ]:
import numpy as np

### 1. 생성 Create

In [ ]:
# numpy array

n = np.array([0, 1, 2, 3, 4, 5])
print(n)

[0 1 2 3 4 5]


In [ ]:
# array reshape

n = n.reshape([2,3])
print(n)

[[0 1 2]
 [3 4 5]]


In [ ]:
a1 = [1, 3, 5]
a2 = [2, 4, 6]

a3 = [a1, a2]

print(a3)

[[1, 3, 5], [2, 4, 6]]


In [ ]:
b1 = np.array(a3)

print(b1)

[[1 3 5]
 [2 4 6]]


In [ ]:
a4 = np.array(range(0, 12, 1))
print(a4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
a5 = np.arange(0, 12, 1)
print(a5)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
a6 = a5.reshape([3, 4])
print(a6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a7 = a6.reshape([2,6])
print(a7)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### 2. 읽기 - Read

- Indexing

In [ ]:
print(b1)

[[1 3 5]
 [2 4 6]]


In [ ]:
b1[0, 0]

1

In [ ]:
b1[1, 2]

6

- Slicing

In [ ]:
b1[0:2, 0]

array([1, 2])

In [ ]:
b1[0, 0:2]

array([1, 3])

In [ ]:
b1[0:2, 0:2]

array([[1, 3],
       [2, 4]])

In [ ]:
b1[0, 0:]

array([1, 3, 5])

In [ ]:
# 불리언 인덱싱

b1[b1>4]

array([5, 6])

In [ ]:
# 불리언 인덱싱
b1[b1<=3]

array([1, 3, 2])

In [ ]:
# 깊은 복사

b2 = b1.copy()
print(b2)

[[1 3 5]
 [2 4 6]]


### Update

In [ ]:
n2 = np.array([6,7])
print(n2)

print(n)
print(n.shape)

[6 7]
[[0 1 2]
 [3 4 5]]
(2, 3)


In [ ]:
n2 = n2.reshape([2,1])
print(n2)
print(n2.shape)

[[6]
 [7]]
(2, 1)


In [ ]:
# 값 추가하기 : 확장은 불가능하고 새로 값을 만들어서 추가해야하만 함
n3 = np.concatenate((n, n2), axis=1) #axis = 1 열 기준으로 붙여라
print(n3)

[[0 1 2 6]
 [3 4 5 7]]


In [ ]:
print(n3.shape)

(2, 4)


In [ ]:
# 값 교체

n3[1, 2] = 9
print(n3)

[[0 1 2 6]
 [3 4 9 7]]


### Delete

In [ ]:
n4 = np.delete(n3, [2,3], 1)
print(n4)

[[0 1]
 [3 4]]


### 3. 계산 Calculation

In [ ]:
# 행렬 곱

b3 = b1 * b2
print(b3)

[[ 1  9 25]
 [ 4 16 36]]


In [ ]:
pip install pandas

In [ ]:
import numpy as np
a = [1, 2, 3]
a2 = [4, 5, 6]
a3 = [7, 8, 9]
n = np.array([a, a2, a3])
print(n.shape)

(3, 3)


In [ ]:
a = [1, 2, 3]

a2 = [4, 5, 6]

a3 = [7, 8, 9]



n = np.array([a, a2, a3])

nums = n[n >= 5]



print(nums)

[5 6 7 8 9]
